name: base-docker-images

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3

  docker-qwak-base:
    runs-on: ubuntu-latest
    env:
      QWAK-VERSION: 0.8.121
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/base-images/qwak/
          file: ./docker/base-images/qwak/Dockerfile
          push: true
          tags: galrabin/qwak:${{ env.QWAK-VERSION }}-py38-gpu,galrabin/qwak:latest-py38

  docker-qwak-gpu-base:
    runs-on: ubuntu-latest
    env:
      QWAK-VERSION: 0.8.121
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/base-images/qwak-gpu/
          file: ./docker/base-images/qwak-gpu/Dockerfile
          push: true
          tags: galrabin/qwak:${{ env.QWAK-VERSION }}-py38-gpu,galrabin/qwak:latest-py38-gpu
