name: base-docker-images

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3

  docker-qwak-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/base-images/qwak/py37
          file: ./docker/base-images/qwak/py37/Dockerfile
          push: true
          tags: qwakai/qwak:py37
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/base-images/qwak/py38
          file: ./docker/base-images/qwak/py38/Dockerfile
          push: true
          tags: qwakai/qwak:py38

  docker-qwak-gpu-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/base-images/qwak-gpu/py37
          file: ./docker/base-images/qwak-gpu/py37/Dockerfile
          push: true
          tags: qwakai/qwak:gpu-py37
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/base-images/qwak-gpu/py38
          file: ./docker/base-images/qwak-gpu/py38/Dockerfile
          push: true
          tags: qwakai/qwak:gpu-py38
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/base-images/qwak-gpu/py39
          file: ./docker/base-images/qwak-gpu/py39/Dockerfile
          push: true
          tags: qwakai/qwak:gpu-py39


  docker-qwak-slim-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/base-images/qwak-slim/py37
          file: ./docker/base-images/qwak-slim/py37/Dockerfile
          push: true
          tags: qwakai/qwak:slim-py37
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/base-images/qwak-slim/py38
          file: ./docker/base-images/qwak-slim/py38/Dockerfile
          push: true
          tags: qwakai/qwakslim-py38
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/base-images/qwak-slim/py38
          file: ./docker/base-images/qwak-slim/py39/Dockerfile
          push: true
          tags: qwakai/qwak:slim-py39
